name: Add Changes Based on Logic

on:
  push:
    branches: [ 'test-action-commit' ]
    paths:
      - 'micro-ui/web/micro-ui-internals/**' # Adjust this to the path of the file you want to monitor changes for

jobs:
  add_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Check Dependency Version
        run: |
          dependency="@egovernments/digit-ui-module-workbench"
          json_file="micro-ui/web/micro-ui-internals/example/package.json"

          # Check if the dependency is present in the package.json file (either in dependencies or devDependencies)
          if jq -e --arg dep "$dependency" '.dependencies[$dep] // .devDependencies[$dep] | strings' "$json_file" >/dev/null; then
            # Check if the version follows semantic versioning and if the third segment is greater than 0
            if jq -e --arg dep "$dependency" '.dependencies[$dep] // .devDependencies[$dep] | test("^[0-9]+\\.[0-9]+\\.[0-9]+$") | . and (. | split(".") | map(tonumber) | .[2] > 0)' "$json_file"; then
              echo "Dependency version incremented"
              # Logic to perform actions when the version is incremented
            else
              echo "No need to update, or the version is not incremented"
              # Logic to perform actions when the version is not incremented
            fi
          else
            echo "Dependency not found in $json_file"
            # Logic to perform actions when the dependency is not found
          fi
