name: Add Changes Based on Logic

on:
  push:
    branches: [ 'test-action-commit' ]
    paths:
      - 'micro-ui/web/micro-ui-internals/**' # Adjust this to the path of the file you want to monitor changes for

jobs:
  add_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Check Dependency Version
        run: |
          dependency="@egovernments/digit-ui-module-workbench"
          json_file="micro-ui/web/micro-ui-internals/example/package.json"
          target_version="1.0.0-beta."

          # Check if the dependency is present in the package.json file
          if jq -e --arg dep "$dependency" '.devDependencies[$dep] | strings' "$json_file" >/dev/null; then
            # Get the current version
            current_version=$(jq -r --arg dep "$dependency" '.devDependencies[$dep]' "$json_file")

            # Check if the version has been incremented from "1.0.0-beta.*"
            if [[ $current_version =~ ^$target_version ]]; then
              echo "Dependency version incremented from $target_version"
              # Logic to perform actions when the version is incremented
            else
              echo "No need to update, or the version is not incremented from $target_version"
              # Logic to perform actions when the version is not incremented from $target_version
            fi
          else
            echo "Dependency not found in $json_file"
            # Logic to perform actions when the dependency is not found
          fi
